apiVersion: v1
kind: ConfigMap
metadata:
  name: g-match-config
  namespace: g-match
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "api.g-match.org,www.g-match.org,localhost"

  DB_NAME: "g-match"
  DB_USER: "django-server"
  DB_HOST: "mysql.g-match.svc.cluster.local"
  DB_PORT: "3306"

  REDIS_HOST: "redis.g-match.svc.cluster.local"
  REDIS_PORT: "6379"

  FRONTEND_URL: "http://www.g-match.org"
  FRONTEND_AUTH_CALLBACK_URL: "http://www.g-match.org/auth/callback"

  GIST_OIDC_CLIENT_ID: "26dbdb53-b19e-4241-9187-f4c24e6173e2"

  GIST_OIDC_REDIRECT_URI: "http://api.g-match.org/api/v1alpha1/account/auth/oidc/callback"
  GIST_OIDC_POST_LOGOUT_REDIRECT_URI: "http://api.g-match.org/api/v1alpha1/account/auth/oidc/callback"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: g-match-matcher-config
  namespace: g-match
data:
  REDIS_HOST: "redis.g-match.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  DB_HOST: "mysql.g-match.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "g-match"
  DB_USER: "django-server"
  EDGE_POLLING_INTERVAL: "10"
  SCHEDULER_INTERVAL: "120"
  MATCH_THRESHOLD: "80.0"
  LOCK_EXPIRE: "120"

