apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "g-match.labels" . | nindent 4 }}
    name: {{ .Release.Namespace }}
    environment: production
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": never
