apiVersion: v1
kind: Secret
metadata:
  name: g-match-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "g-match.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": never
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  DB_ROOT_PASSWORD: {{ .Values.secrets.dbRootPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  GIST_OIDC_CLIENT_SECRET: {{ .Values.secrets.gistOidcClientSecret | quote }}
